server:
  port: 8001
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
      #password:
    #cluster:
    #nodes: 172.16.67.35:6000,172.16.67.36:6000,172.16.67.37:6000,172.16.67.38:6000,172.16.67.39:6000,172.16.67.40:6000
    #max-redirects: 6
    lettuce:
      pool:
        max-active: 300
        max-idle: 100
        min-idle: 0
        max-wait: -1ms
    timeout: 10000ms
    database: 1